use sdl2::keyboard::Keycode;

pub fn get_alpha_numeric(code: &Keycode) -> Option<&'static str> {
    match code {
        Keycode::Space { .. } => Some(&" "),
        Keycode::Period { .. } => Some(&"."),
        Keycode::A { .. } => Some(&"A"),
        Keycode::B { .. } => Some(&"B"),
        Keycode::C { .. } => Some(&"C"),
        Keycode::D { .. } => Some(&"D"),
        Keycode::E { .. } => Some(&"E"),
        Keycode::F { .. } => Some(&"F"),
        Keycode::G { .. } => Some(&"G"),
        Keycode::H { .. } => Some(&"H"),
        Keycode::I { .. } => Some(&"I"),
        Keycode::J { .. } => Some(&"J"),
        Keycode::K { .. } => Some(&"K"),
        Keycode::L { .. } => Some(&"L"),
        Keycode::M { .. } => Some(&"M"),
        Keycode::N { .. } => Some(&"N"),
        Keycode::O { .. } => Some(&"O"),
        Keycode::P { .. } => Some(&"P"),
        Keycode::Q { .. } => Some(&"Q"),
        Keycode::R { .. } => Some(&"R"),
        Keycode::S { .. } => Some(&"S"),
        Keycode::T { .. } => Some(&"T"),
        Keycode::U { .. } => Some(&"U"),
        Keycode::V { .. } => Some(&"V"),
        Keycode::W { .. } => Some(&"W"),
        Keycode::X { .. } => Some(&"X"),
        Keycode::Y { .. } => Some(&"Y"),
        Keycode::Z { .. } => Some(&"Z"),
        Keycode::Num0 { .. } => Some(&"0"),
        Keycode::Num1 { .. } => Some(&"1"),
        Keycode::Num2 { .. } => Some(&"2"),
        Keycode::Num3 { .. } => Some(&"3"),
        Keycode::Num4 { .. } => Some(&"4"),
        Keycode::Num5 { .. } => Some(&"5"),
        Keycode::Num6 { .. } => Some(&"6"),
        Keycode::Num7 { .. } => Some(&"7"),
        Keycode::Num8 { .. } => Some(&"8"),
        Keycode::Num9 { .. } => Some(&"9"),
        _ => None,
    }
}
