[package]
name = "rust-sdl2-pixel"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug_print_feature = []

[dependencies]
crossterm = "0.21.0"
once_cell = "1.8.0"
libmath = "0.2.1"
bytemuck = "*"

[dependencies.sdl2]
version = "0.34"
default-features = false
# features = ["gfx","image"]

# [profile.dev]
# opt-level = 0

# [profile.release]
# opt-level = 3
