pub mod albedo_fragment_shader;
pub mod depth_fragment_shader;
pub mod emissive_fragment_shader;
pub mod metallic_fragment_shader;
pub mod normal_fragment_shader;
pub mod roughness_fragment_shader;
pub mod specular_roughness_fragment_shader;
pub mod stencil_fragment_shader;
pub mod uv_test_fragment_shader;
